name: Linx Digital NPM Publish

on:
  push:
    branches: [ $default-branch ]
  
  workflow_dispatch:
    inputs:
      input:
        description: "Run workflow manually"
        required: false
        default: "run"

jobs:
  # Job to fill CUSTOM_ENV_VARS with desired values, you can use it to pass some secrets as a parameter to
  # next job execution.
  #
  # Build-Custom-Env-Vars:
  #   name: build custom env var
  #   runs-on: ubuntu-latest
  #   outputs:
  #     CUSTOM_ENV_VARS: ${{steps.create_var_envs.outputs.CUSTOM_ENV_VARS}}
  #   steps:
  #     - name: create custom env var object
  #       id: create_var_envs
  #       env: 
  #         VUE_APP_STATIC_PATH: ${{secrets.VUE_APP_STATIC_PATH}}
  #         STG_VUE_APP_API_BASE_URL: ${{secrets.STG_VUE_APP_API_BASE_URL}}
  #       run: |
  #         CUSTOM_ENV_VARS=$(echo "{\"NAME\":\"CUSTOM_ENV_VARS\",\"VUE_APP_STATIC_PATH\": \"${VUE_APP_STATIC_PATH}\", \"VUE_APP_API_BASE_URL\": \"${STG_VUE_APP_API_BASE_URL}\"}"| base64 -w0)
  #         echo "CUSTOM_ENV_VARS=$CUSTOM_ENV_VARS" >> $GITHUB_OUTPUT;

  lint-build-deploy:
    uses: chaordic/github-workflows-templates/.github/workflows/typescript-npm-publish.yml@main
    secrets:
      NPM_TOKEN: <NPM Token to access private NPM repository>
      PUSH_TOKEN: <Github Tonken to make Push on repositories when it need an special permission>
      SLACK_WEBHOOK: <Slack Webhook configuration>
      # The CUSTOM_ENV_VARS on inputs has preference over CUSTOM_ENV_VARS on secrets
      CUSTOM_ENV_VARS: "<JSON Object encoded on base64 with custom environment variables, The FirstKey must be \"NAME\":\"CUSTOM_ENV_VARS\", eg: {\"NAME\":\"CUSTOM_ENV_VARS\",\"VUE_APP_STATIC_PATH\":\"/path/to/locale/\",\"VUE_APP_API_BASE_URL\":\"/baseulr.com.br/\"}>"
    with:
      ARTIFACT_DIR: dist
      CUSTOM_BUILD_COMMAND: <custom command to run build, not required>
      CUSTOM_INSTALL_COMMAND: <Custom command to install project dependencies, not required>
      CUSTOM_LINT_COMMAND: <Custom command to run lint, not required>
      CUSTOM_TEST_COMMAND: <Custom command to call project tests>
      # The CUSTOM_ENV_VARS on inputs has preference over CUSTOM_ENV_VARS on secrets
      # you can use the value ${{needs.Build-Custom-Env-Vars.outputs.CUSTOM_ENV_VARS}} if you mount
      # this value on this workflow
      #
      # eg: CUSTOM_ENV_VARS: ${{needs.Build-Custom-Env-Vars.outputs.CUSTOM_ENV_VARS}}
      CUSTOM_ENV_VARS: "<JSON Object encoded on base64 with custom environment variables, The FirstKey must be \"NAME\":\"CUSTOM_ENV_VARS\", eg: {\"NAME\":\"CUSTOM_ENV_VARS\",\"VUE_APP_STATIC_PATH\":\"/path/to/locale/\",\"VUE_APP_API_BASE_URL\":\"/baseulr.com.br/\"}>"
      MATRIX_NODE_VERSION: "<An String with JSON Array with Matrix Node version, eg: \"[\"18.x\",\"14.x\"]\", default: \"[\"18.x\"]\">"
      SLACK_NOTIFICATION_ENABLED: <true|false>

