name: NPM Build and Publish

on:
  push:
    branches: [ $default-branch ]
  
  workflow_dispatch:
    inputs:
      input:
        description: "Run workflow manually"
        required: false
        default: "run"

jobs:
  lint-build-deploy:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo Hello from Octo Organization
