name: NPM Build and Publish

on:
  push:
    branches: ['main']
  
  workflow_dispatch:
    inputs:
      input:
        description: "Run workflow manually"
        required: false
        default: "run"

jobs:
  lint-build-deploy:
    uses: chaordic/github-workflows-templates/.github/workflows/typescript-npm-publish.yml@main
    secrets: inherit
