name: Linx Digital Typescript S3 Cloud Front Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc.*"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.*"
    
  workflow_dispatch:
    inputs:
      input:
         description: "Run workflow manually"
         required: false
         default: "run"


jobs:
  # Job to fill CUSTOM_ENV_VARS with desired values, you can use it to pass some secrets as a parameter to
  # next job execution.
  #
  # Build-Custom-Env-Vars:
  #   name: build custom env var
  #   runs-on: ubuntu-latest
  #   outputs:
  #     CUSTOM_ENV_VARS: ${{steps.create_var_envs.outputs.CUSTOM_ENV_VARS}}
  #   steps:
  #     - name: create custom env var object
  #       id: create_var_envs
  #       env: 
  #         VUE_APP_STATIC_PATH: ${{secrets.VUE_APP_STATIC_PATH}}
  #         STG_VUE_APP_API_BASE_URL: ${{secrets.STG_VUE_APP_API_BASE_URL}}
  #       run: |
  #         CUSTOM_ENV_VARS=$(echo "{\"NAME\":\"CUSTOM_ENV_VARS\",\"VUE_APP_STATIC_PATH\": \"${VUE_APP_STATIC_PATH}\", \"VUE_APP_API_BASE_URL\": \"${STG_VUE_APP_API_BASE_URL}\"}"| base64 -w0)
  #         echo "CUSTOM_ENV_VARS=$CUSTOM_ENV_VARS" >> $GITHUB_OUTPUT;

  S3-CF-deploy:
    uses: chaordic/github-workflows-templates/.github/workflows/typescript-s3-deploy.yml@main
    needs: Build-Custom-Env-Vars
    secrets:
      AWS_ACCESS_KEY_ID: <your AWS Access Key id>
      AWS_SECRET_ACCESS_KEY: <your AWS Access Key id>
      # AWS_CF_DISTRIBUTION_ID if not provided the invalidation step will be skipped
      AWS_CF_DISTRIBUTION_ID: <Your project Cloud Front Distribution ID>
      # The CUSTOM_ENV_VARS on inputs has preference over CUSTOM_ENV_VARS on secrets
      CUSTOM_ENV_VARS: "<JSON Object encoded on base64 with custom environment variables, The FirstKey must be \"NAME\":\"CUSTOM_ENV_VARS\", eg: {\"NAME\":\"CUSTOM_ENV_VARS\",\"VUE_APP_STATIC_PATH\":\"/path/to/locale/\",\"VUE_APP_API_BASE_URL\":\"/baseulr.com.br/\"}>"
      NPM_TOKEN: <NPM Token to access private NPM repository>
      SLACK_WEBHOOK: <Slack Webhook configuration>
      
    with:
      # directory with files that will be saved to github artifacts, default: dist
      ARTIFACT_DIR: dist
      AWS_REGION: "us-east-1"
      AWS_S3_BUCKET: <your S3 bucket name>
      CF_PATHS: "<paths to invalidate cache, separated by space, eg: '/foo /bar /*'>"
      # DEST_DIR default value / root of bucket
      DEST_DIR: <S3 directory destination>

      # The CUSTOM_ENV_VARS on inputs has preference over CUSTOM_ENV_VARS on secrets
      # you can use the value ${{needs.Build-Custom-Env-Vars.outputs.CUSTOM_ENV_VARS}} if you mount
      # this value on this workflow
      #
      # eg: CUSTOM_ENV_VARS: ${{needs.Build-Custom-Env-Vars.outputs.CUSTOM_ENV_VARS}}
      CUSTOM_ENV_VARS: "<JSON Object encoded on base64 with custom environment variables, The FirstKey must be \"NAME\":\"CUSTOM_ENV_VARS\", eg: {\"NAME\":\"CUSTOM_ENV_VARS\",\"VUE_APP_STATIC_PATH\":\"/path/to/locale/\",\"VUE_APP_API_BASE_URL\":\"/baseulr.com.br/\"}>"
      CUSTOM_TEST_COMMAND: <Custom command to call project tests>
      CUSTOM_INSTALL_COMMAND: <Custom command to install project dependencies, not required>
      CUSTOM_LINT_COMMAND: <Custom command to run lint, not required>
      CUSTOM_BUILD_COMMAND: <custom command to run build, not required>
      # MATRIX_NODE_VERSION: Default value ["18.x"]
      MATRIX_NODE_VERSION: "<An String with JSON Array with Matrix Node version, eg: \"[\"18.x\",\"14.x\"]\", default: \"[\"18.x\"]\">"
      # S3_CUSTOM_ARGS: default value --follow-symlinks
      S3_CUSTOM_ARGS: "arguments to run aws s3 cli command"
      # SOURCE_DIR: default value dist
      SOURCE_DIR: <path to source directory to upload file to S3>
      # SLACK_NOTIFICATION_ENABLED: default value "false"
      SLACK_NOTIFICATION_ENABLED: "true"
